/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gitadatabase;

import java.util.ArrayList;

/**
 *
 * @author taboada.taddeo
 */
public class AggiuntaStudente extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AggiuntaStudente.class.getName());
    private String nome, cognome;
    private Classe classe;
    private Gita gita;
    private ArrayList<Classe> classi;
    private ArrayList<Gita> gite;

    /**
     * Creates new form AggiuntaStudente
     */
    public AggiuntaStudente(java.awt.Frame parent, boolean modal, ArrayList<Classe> classi, ArrayList<Gita> gite) {
        super(parent, modal);    
        this.classi = classi;
        this.gite = gite;
        initComponents();
        riempiClassi();
        riempiGite();
    }
    
    private void riempiClassi() {
        cmbClassi.removeAllItems();
        for (Classe c : classi) cmbClassi.addItem(c.toString());
    }
 
    private void riempiGite() {
        cmbGite.removeAllItems();
        for (Gita g : gite) cmbGite.addItem(g.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlTitolo = new javax.swing.JPanel();
        lblTitolo = new javax.swing.JLabel();
        pnlCentro = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCognome = new javax.swing.JLabel();
        txtCognome = new javax.swing.JTextField();
        lblGita = new javax.swing.JLabel();
        cmbGite = new javax.swing.JComboBox<>();
        lblClasse = new javax.swing.JLabel();
        cmbClassi = new javax.swing.JComboBox<>();
        pnlConferma = new javax.swing.JPanel();
        btnConferma = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aggiungi uno Studente");
        setMinimumSize(new java.awt.Dimension(500, 350));

        pnlTitolo.setBackground(new java.awt.Color(153, 255, 255));
        pnlTitolo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlTitolo.setLayout(new java.awt.BorderLayout());

        lblTitolo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("Aggiungi uno Studente!");
        pnlTitolo.add(lblTitolo, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlTitolo, java.awt.BorderLayout.PAGE_START);

        pnlCentro.setBackground(new java.awt.Color(153, 255, 255));
        pnlCentro.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlCentro.setLayout(new java.awt.GridLayout(4, 2, 10, 10));

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNome.setText("Nome:");
        pnlCentro.add(lblNome);

        txtNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnlCentro.add(txtNome);

        lblCognome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCognome.setText("Cognome:");
        pnlCentro.add(lblCognome);

        txtCognome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnlCentro.add(txtCognome);

        lblGita.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGita.setText("Gita:");
        pnlCentro.add(lblGita);

        pnlCentro.add(cmbGite);

        lblClasse.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblClasse.setText("Classe:");
        pnlCentro.add(lblClasse);

        pnlCentro.add(cmbClassi);

        getContentPane().add(pnlCentro, java.awt.BorderLayout.CENTER);

        pnlConferma.setBackground(new java.awt.Color(153, 255, 255));
        pnlConferma.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlConferma.setLayout(new java.awt.BorderLayout());

        btnConferma.setBackground(new java.awt.Color(102, 255, 102));
        btnConferma.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnConferma.setText("Conferma");
        btnConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfermaActionPerformed(evt);
            }
        });
        pnlConferma.add(btnConferma, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlConferma, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfermaActionPerformed
        nome = txtNome.getText();
        cognome = txtCognome.getText();
        int idxClasse = cmbClassi.getSelectedIndex();
        int idxGita = cmbGite.getSelectedIndex();
        classe = classi.get(idxClasse);
        gita = gite.get(idxGita);
        dispose();
    }//GEN-LAST:event_btnConfermaActionPerformed

    public String getNome() {
        return nome;
    }

    public String getCognome() {
        return cognome;
    }

    public Classe getClasse() {
        return classe;
    }
    
    public Gita getGita() {
        return gita;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConferma;
    private javax.swing.JComboBox<String> cmbClassi;
    private javax.swing.JComboBox<String> cmbGite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblClasse;
    private javax.swing.JLabel lblCognome;
    private javax.swing.JLabel lblGita;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlConferma;
    private javax.swing.JPanel pnlTitolo;
    private javax.swing.JTextField txtCognome;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
