/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gitadatabase;

/**
 *
 * @author taboada.taddeo
 */
public class AggiuntaClasse extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AggiuntaClasse.class.getName());
    private Classe c;

    /**
     * Creates new form AggiuntaClasse
     */
    public AggiuntaClasse(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.c = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitolo = new javax.swing.JPanel();
        lblTitolo = new javax.swing.JLabel();
        pnlCentro = new javax.swing.JPanel();
        lblAnno = new javax.swing.JLabel();
        txtAnno = new javax.swing.JTextField();
        lblSezione = new javax.swing.JLabel();
        txtSezione = new javax.swing.JTextField();
        lblIndirizzo = new javax.swing.JLabel();
        txtIndirizzo = new javax.swing.JTextField();
        pnlConferma = new javax.swing.JPanel();
        btnConferma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aggiunta Classe");
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));

        pnlTitolo.setBackground(new java.awt.Color(153, 255, 255));
        pnlTitolo.setLayout(new java.awt.BorderLayout());

        lblTitolo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("Aggiungi una Classe!");
        pnlTitolo.add(lblTitolo, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlTitolo, java.awt.BorderLayout.PAGE_START);

        pnlCentro.setBackground(new java.awt.Color(153, 255, 255));
        pnlCentro.setLayout(new java.awt.GridLayout(3, 2, 10, 10));

        lblAnno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAnno.setText("Anno:");
        pnlCentro.add(lblAnno);

        txtAnno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnlCentro.add(txtAnno);

        lblSezione.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSezione.setText("Sezione:");
        pnlCentro.add(lblSezione);

        txtSezione.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnlCentro.add(txtSezione);

        lblIndirizzo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIndirizzo.setText("Indirizzo:");
        pnlCentro.add(lblIndirizzo);

        txtIndirizzo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnlCentro.add(txtIndirizzo);

        getContentPane().add(pnlCentro, java.awt.BorderLayout.CENTER);

        pnlConferma.setBackground(new java.awt.Color(153, 255, 255));
        pnlConferma.setLayout(new java.awt.BorderLayout());

        btnConferma.setBackground(new java.awt.Color(102, 255, 102));
        btnConferma.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnConferma.setText("Conferma");
        btnConferma.addActionListener(this::btnConfermaActionPerformed);
        pnlConferma.add(btnConferma, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlConferma, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfermaActionPerformed
        int anno = Integer.parseInt(txtAnno.getText());
        String sezione = txtSezione.getText();
        String indirizzo = txtIndirizzo.getText();
        
        c = new Classe(anno, sezione, indirizzo);
        
        dispose();
    }//GEN-LAST:event_btnConfermaActionPerformed

    public Classe getC() {
        return c;
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConferma;
    private javax.swing.JLabel lblAnno;
    private javax.swing.JLabel lblIndirizzo;
    private javax.swing.JLabel lblSezione;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlConferma;
    private javax.swing.JPanel pnlTitolo;
    private javax.swing.JTextField txtAnno;
    private javax.swing.JTextField txtIndirizzo;
    private javax.swing.JTextField txtSezione;
    // End of variables declaration//GEN-END:variables
}
