/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gitadatabase;

/**
 *
 * @author taboada.taddeo
 */
public class AggiuntaGita extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AggiuntaGita.class.getName());
    private String luogo;
    private int id;
    private int durata;
    private int prezzo;

    /**
     * Creates new form AggiuntaGita
     */
    public AggiuntaGita(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitolo = new javax.swing.JPanel();
        lblTitolo = new javax.swing.JLabel();
        pnlCentro = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblLuogo = new javax.swing.JLabel();
        txtLuogo = new javax.swing.JTextField();
        lblDurata = new javax.swing.JLabel();
        txtDurata = new javax.swing.JTextField();
        lblPrezzo = new javax.swing.JLabel();
        txtPrezzo = new javax.swing.JTextField();
        pnlConferma = new javax.swing.JPanel();
        btnConferma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aggiungi una Gita");
        setMinimumSize(new java.awt.Dimension(500, 350));
        getContentPane().setLayout(new java.awt.BorderLayout());

        pnlTitolo.setBackground(new java.awt.Color(153, 255, 255));
        pnlTitolo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlTitolo.setLayout(new java.awt.BorderLayout());

        lblTitolo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("Aggiungi una Gita!");
        pnlTitolo.add(lblTitolo, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlTitolo, java.awt.BorderLayout.PAGE_START);

        pnlCentro.setBackground(new java.awt.Color(153, 255, 255));
        pnlCentro.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlCentro.setLayout(new java.awt.GridLayout(4, 2, 10, 10));

        lblId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblId.setText("ID:");
        pnlCentro.add(lblId);

        txtId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnlCentro.add(txtId);

        lblLuogo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLuogo.setText("Luogo:");
        pnlCentro.add(lblLuogo);

        txtLuogo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnlCentro.add(txtLuogo);

        lblDurata.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDurata.setText("Durata:");
        pnlCentro.add(lblDurata);

        txtDurata.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnlCentro.add(txtDurata);

        lblPrezzo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrezzo.setText("Prezzo:");
        pnlCentro.add(lblPrezzo);

        txtPrezzo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnlCentro.add(txtPrezzo);

        getContentPane().add(pnlCentro, java.awt.BorderLayout.CENTER);

        pnlConferma.setBackground(new java.awt.Color(153, 255, 255));
        pnlConferma.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlConferma.setLayout(new java.awt.BorderLayout());

        btnConferma.setBackground(new java.awt.Color(102, 255, 102));
        btnConferma.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnConferma.setText("Conferma");
        btnConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfermaActionPerformed(evt);
            }
        });
        pnlConferma.add(btnConferma, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlConferma, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfermaActionPerformed
        id = Integer.parseInt(txtId.getText());
        luogo = txtLuogo.getText();
        durata = Integer.parseInt(txtDurata.getText());
        prezzo = Integer.parseInt(txtPrezzo.getText());
        
        dispose();
    }//GEN-LAST:event_btnConfermaActionPerformed

    public String getLuogo() {
        return luogo;
    }

    public int getId() {
        return id;
    }

    public int getDurata() {
        return durata;
    }

    public int getPrezzo() {
        return prezzo;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConferma;
    private javax.swing.JLabel lblDurata;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLuogo;
    private javax.swing.JLabel lblPrezzo;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlConferma;
    private javax.swing.JPanel pnlTitolo;
    private javax.swing.JTextField txtDurata;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLuogo;
    private javax.swing.JTextField txtPrezzo;
    // End of variables declaration//GEN-END:variables
}
